name: Push Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3
      with:
        ref: 'master'
        repository: 'github-actions/starting-project'
        path: 'starting-project'

    - name: Change Directory
      run: |
        cd github-actions/starting-project
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with: 
        node-version: 18  # Adjust the version as needed

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
